# Generated by Django 6.0.2 on 2026-03-15 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_location_building'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='name',
        ),
    ]
