# Generated by Django 6.0.2 on 2026-03-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_remove_device_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
