# Generated by Django 6.0.2 on 2026-05-12 19:05

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
